name: Deploy Backend con Docker

on:
  push:
    branches: [ "BlackDev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Ejecutar despliegue Docker en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app
            
            # Clonar o actualizar la rama BlackDev
            if [ ! -d ".git" ]; then
              git clone -b BlackDev https://github.com/${{ github.repository }}.git .
            else
              git fetch origin BlackDev
              git reset --hard origin/BlackDev
            fi
            
            # Construir imagen Multi-Stage
            cd pedidos360-backend
            docker build -t pedidos360-backend .
            
            # Reemplazar contenedor
            docker stop pedidos360-backend || true
            docker rm pedidos360-backend || true
            docker run -d --name pedidos360-backend -p 8080:8080 --restart unless-stopped pedidos360-backend