name: Deploy Backend con Docker

on:
  push:
    branches: [ "BlackDev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Ejecutar despliegue Docker en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Verificar instalación de Git
            which git || sudo dnf install -y git
            
            # 2. Gestionar la carpeta /home/ec2-user/app limpia
            if [ -d "/home/ec2-user/app/.git" ]; then
              cd /home/ec2-user/app
              git fetch origin BlackDev
              git reset --hard origin/BlackDev
            else
              rm -rf /home/ec2-user/app
              git clone -b BlackDev https://github.com/${{ github.repository }}.git /home/ec2-user/app
              cd /home/ec2-user/app
            fi
            
            # 3. Construir la imagen Multi-Stage
            cd pedidos360-backend
            docker build -t pedidos360-backend .
            
            # 4. Desplegar el contenedor
            docker stop pedidos360-backend || true
            docker rm pedidos360-backend || true
            docker run -d --name pedidos360-backend -p 8080:8080 --restart unless-stopped pedidos360-backend